# -*- coding: utf-8 -*-
"""Putty_Dhathri_Flam_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4L2iaxkIjxA35zLlcQFS4x--p4EeD_E
"""

# Step 1️ : Import all required libraries
# ---------------------------------------
import pandas as pd
import numpy as np
import math

#Step 2: Import dataset
data_path = "/content/drive/MyDrive/xy_data.csv"

# Read CSV file containing columns x and y
tab_data = pd.read_csv(data_path)

# Verify data was read correctly
print(tab_data.head())
print("Shape of data →", tab_data.shape)

# Step 3️ : Generate equally spaced t values
# Range of t is 6 < t < 60, same number as rows in the dataset
t_series = np.linspace(6, 60, len(tab_data))
print("Number of t values →", len(t_series))

# Step 4️ : Define the curve from given parametric equations
# ------------------------------------------------------------
def make_curve(t_arr, theta_val, M_val, X_val):
    # Compute predicted x and y coordinates
    x_pred = t_arr * np.cos(theta_val) - np.exp(M_val * np.abs(t_arr)) * np.sin(0.3 * t_arr) * np.sin(theta_val) + X_val
    y_pred = 42 + t_arr * np.sin(theta_val) + np.exp(M_val * np.abs(t_arr)) * np.sin(0.3 * t_arr) * np.cos(theta_val)
    return x_pred, y_pred

# Step 5️ : Define the total L1 error (sum of absolute differences)
# -------------------------------------------------------------------
def total_error(param_list):
    theta_val, M_val, X_val = param_list
    pred_x, pred_y = make_curve(t_series, theta_val, M_val, X_val)
    err_sum = np.sum(np.abs(tab_data['x'] - pred_x)) + np.sum(np.abs(tab_data['y'] - pred_y))
    return err_sum

# Step 6️⃣ : Search for best values of θ, M, and X using simple grid search
# -------------------------------------------------------------------------
theta_list = np.deg2rad(np.linspace(0, 50, 25))   # θ in radians (0°–50°)
M_list = np.linspace(-0.05, 0.05, 15)             # M range
X_list = np.linspace(0, 100, 15)                  # X range

best_error = float('inf')
best_values = None

# Brute-force search (kept simple for clarity)
for th in theta_list:
    for m in M_list:
        for xsh in X_list:
            current_error = total_error([th, m, xsh])
            if current_error < best_error:
                best_error = current_error
                best_values = [th, m, xsh]

print("You have Found Best values:")
print("Theta (radians):", best_values[0])
print("M:", best_values[1])
print("X:", best_values[2])
print("Minimum error:", best_error)

